### ISSUE TITLE
[Bug] All bugs and issues?

### ISSUE THREAD

**Issue by Sheeeeit** [pierrelasse/YimStuff#11] opened 2023-12-25 21:49 UTC
I realize that some of the functions currently do not work or do not work as originally intended, but as a user of this script, I would like to create this thread, where all the problems with buttons, tabs, checkboxes will be collected here.

 I am currently having problems with these points:
 - stock replenishment shows up in the console: `[21:31:55.2158136][WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.`
 - for Cayo all skips (grate, hack, prints, plasma cutter) and setting percentages for players don't work
 - for Casino all skips (fingerprint, keypad, drill) don't work
 - if you try to check the $2M checkbox for agency the game will close without logs in the console

I have plans to add to this thread with other problems that may be discovered during use. Thanks!

---

<details>
  <summary>Correct work (exactly what I tried)</summary>

-  select target and approach for heist (only casino and cayo tested)
-  block explosion shake (this thing really help me lot times)
-  refill popularity and "pay now" in Nightclub
-  all quick actions (it would be useful if buttons could be adjusted to the size of this window when it is changed) 

</details>

**Comment by pierrelasse** [comment] 2023-12-26 09:59
Hello,

i don't know if you are using the newest version but the entire HBO section is marked as not working and i will have to redo most of the things.

For the native exception, i will take a look at where the error is caused and i will try fixing it.

> all quick actions (it would be useful if buttons could be adjusted to the size of this window when it is changed)
It would be cool if you could edit what is there like drag the buttons/actions there. But i don't know if it's possible and if so how hard it is to do.

*block explosion shake op af*

**Comment by pierrelasse** [comment] 2023-12-30 15:44
Further native erros also should be fixed with this commit https://github.com/pierrelasse/YimStuff/commit/b062bc9ca388fd8ba52d40f3b7f3acc0fd19935d

**Comment by pierrelasse** [comment] 2023-12-31 08:32
I will redo the warehouse section in Online->Thing.
It will be a better version wich will be better to understand.
The current version in the HBO tab was made like in 2 min so it is not very well made.

**Comment by pierrelasse** [comment] 2024-01-02 11:43
> `Online -> CMM -> SecuroServ (Office)` no fill in-game data

Issue confirmed. I will redo the CMM stuff soon i hope.

**Comment by pierrelasse** [comment] 2024-01-06 20:37
Okay so the SecuroServ CMM is kinda useless, because you can already access it through the Mastercontrol which you can find in the list.

**Comment by pierrelasse** [comment] 2024-04-19 19:09
If you found new bugs, please open a new issue,

**Closed by pierrelasse** 2024-04-19 19:09 UTC
Labels: bug
